services:
    postgres:
        image: postgres:13
        container_name: postgres-db
        restart: always
        environment:
            POSTGRES_DB: 65pin3
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 40022120
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    backend:
        # build:
        #     context: ./backend/project
        image: ramonjosep/65pin3:backend
        container_name: backend-app
        depends_on:
            - postgres
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/65pin3
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: 40022120
        ports:
            - "8080:8080"

    frontend:
        # build:
        #     context: ./frontend
        image: ramonjosep/65pin3:frontend
        container_name: frontend-app
        ports:
            - "3000:3000"
        depends_on:
            - backend

volumes:
    postgres_data:
